name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build Debug APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # Use Gradle Action (downloads Gradle if no wrapper present)
      - name: Run Gradle build (assembleDebug)
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :app:assembleDebug --no-daemon
          # gradle-version: '9.1'  # 必要に応じて固定する（省略可）

      - name: Upload APK Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk