name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # Gradle をリポジトリ内の wrapper ではなく、Actions側で用意して使う
      - name: Set up Gradle 8.9 (no wrapper)
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.9

      - name: Clean build
        run: gradle --no-daemon clean

      # モジュール名が app ならそのまま。違う場合は :<モジュール名>:assembleDebug に変更
      - name: Build debug APK
        run: gradle :app:assembleDebug --stacktrace --info

      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/*.apk
