- name: Make gradlew executable
        run: chmod +x ./gradlew

        - name: Clean Gradle cache
        run: rm -rf ~/.gradle/caches

      - name: Build debug APK
        run: ./gradlew assembleDebug --stacktrace --info

name: Android Persona Build
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle (no wrapper)
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.9
          cache-read-only: false

      - name: Build debug APK
        run: |
          gradle :app:assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/*.apk
