name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: チェックアウト
        uses: actions/checkout@v4

      - name: JDK 17 をセットアップ
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Gradle をセットアップ（キャッシュ）
        uses: gradle/actions/setup-gradle@v3

      - name: ルート Gradle ファイル同期
        run: |
          cp -f ".github/workflows/build.gradle.kts" ./build.gradle.kts
          cp -f ".github/workflows/settings.gradle.kts" ./settings.gradle.kts
          cp -f ".github/workflows/gradle.properties" ./gradle.properties
          rsync -a ".github/workflows/engine/" ./
          chmod +x ./gradlew
          ./gradlew --version

      - name: ビルド
        run: ./gradlew assembleDebug --stacktrace

      - name: APK アップロード
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/*.apk
