name: Android Persona Build

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    name: Build Persona APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build Release APK
        run: ./gradlew assembleRelease --no-daemon --stacktrace

      - name: Upload built APK
        uses: actions/upload-artifact@v4
        with:
          name: Persona-Release
          path: app/build/outputs/apk/release/*.apk
