- name: Debug repo layout
        run: |
          echo "::group::PWD / Tree"
          pwd
          ls -la
          echo "::endgroup::"

          echo "::group::Find app candidates"
          find . -maxdepth 3 -type d -name app | sed 's,^,FOUND: ,'
          echo "::endgroup::"

          echo "::group::Gradle files"
          ls -la settings.gradle* || true
          ls -la */settings.gradle* || true
          ls -la build.gradle* || true
          echo "::endgroup::"

          echo "::group::Fail if no app dir"
          if ! [ -d ./app ] && ! [ -d ./kt/app ]; then
            echo "ERROR: ./app も ./kt/app も無い。settings で指す先が存在しない。" >&2
            exit 2
          fi
          echo "::endgroup::"
