name: Bootstrap Gradle Wrapper
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  add-wrapper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install Gradle (no wrapper yet)
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.9'

      - name: Generate and commit Gradle wrapper
        run: |
          gradle wrapper --gradle-version 8.9
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add gradlew gradlew.bat gradle/wrapper/gradle-wrapper.jar gradle/wrapper/gradle-wrapper.properties
          git commit -m "Add Gradle wrapper 8.9"
          git push
