name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - uses: gradle/actions/setup-gradle@v3

      # 1) プロジェクト座標の自動検出（kt/ があれば kt、なければルート）
      - name: Detect project dir
        id: detect
        run: |
          set -e
          PROJ="."
          [ -d kt/app ] && PROJ="kt"
          echo "proj=$PROJ" >> $GITHUB_OUTPUT
          echo "Detected project dir: $PROJ"

      # 2) wrapper を自己回復（無い/壊れてる/改行おかしい すべて面倒見る）
      - name: Ensure Gradle wrapper
        run: |
          set -e
          PROJ="${{ steps.detect.outputs.proj }}"
          WRAP="gradlew"
          [ "$PROJ" != "." ] && WRAP="$PROJ/gradlew"

          # 2KB未満＝壊れ（YAML等）の可能性 → 削除
          if [ -f "$WRAP" ] && [ $(wc -c <"$WRAP") -lt 2000 ]; then
            echo "Wrapper seems broken, removing..."
            rm -f "$WRAP"
          fi

          if [ ! -f "$WRAP" ]; then
            echo "No wrapper -> bootstrap Gradle 8.7"
            curl -sL https://services.gradle.org/distributions/gradle-8.7-bin.zip -o g.zip
            unzip -q g.zip
            ./gradle-8.7/bin/gradle -p "$PROJ" wrapper --gradle-version 8.7
          fi

          # CRLF→LF & 実行権限
          sed -i 's/\r$//' "$WRAP" || true
          chmod +x "$WRAP"

          echo "WRAP=$WRAP" >> $GITHUB_ENV
          echo "PROJ=$PROJ" >> $GITHUB_ENV
          echo "Wrapper ready at: $WRAP (project=$PROJ)"

      # 3) 落ち着いてビルド（座標固定、非並列、ワーカー1本）
      - name: Build debug APK
        run: |
          $WRAP -p "$PROJ" --no-daemon --no-parallel --max-workers=1 \
            --stacktrace clean assembleDebug

      # 4) どちらの配置でもAPKを拾う（無ければ無視）
      - name: Upload APK (kt/)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-kt
          path: kt/app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: ignore

      - name: Upload APK (root app/)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-root
          path: app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: ignore
