name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Gradle cache
        uses: gradle/actions/setup-gradle@v3

      # ▼ ここがミソ：wrapper が無ければ自動で“復活”させる
      - name: Bootstrap Gradle 8.7 if wrapper is missing
        run: |
          set -e
          if [ ! -f gradlew ] && [ ! -f kt/gradlew ]; then
            echo "No wrapper found. Bootstrapping Gradle 8.7..."
            curl -sL https://services.gradle.org/distributions/gradle-8.7-bin.zip -o gradle.zip
            unzip -q gradle.zip
            # プロジェクトが kt/ 配下想定。違う場合は -p . に変えてOK
            ./gradle-8.7/bin/gradle -p kt wrapper --gradle-version 8.7
          fi

      - name: Make wrapper executable
        run: |
          if [ -f kt/gradlew ]; then
            chmod +x kt/gradlew
          elif [ -f gradlew ]; then
            chmod +x gradlew
          else
            echo "gradlew not found after bootstrap" && exit 1
          fi

      - name: Build Debug APK (project-dir auto)
        run: |
          set -e
          WRAP="./gradlew"; PROJ="."
          if [ -f kt/gradlew ]; then WRAP="./kt/gradlew"; PROJ="kt"; fi
          "$WRAP" -p "$PROJ" --no-daemon --no-parallel --max-workers=1 clean assembleDebug

      # kt/ 配下と通常 app/ の両方をカバー（無ければ無視）
      - name: Upload APK (kt/)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-kt
          path: kt/app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: ignore

      - name: Upload APK (root app/)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-root
          path: app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: ignore