name: Android CI (no-wrapper)

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      # ① ソース取得
      - uses: actions/checkout@v4

      # ② JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # ③ Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # ④ SDK ライセンス & 必要パッケージ
      - name: Accept SDK licenses & install
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platforms;android-34" "build-tools;34.0.0"

      # ⑤ Gradle 8.7 を取得して展開
      - name: Download Gradle 8.7
        run: |
          curl -sLo gradle.zip https://services.gradle.org/distributions/gradle-8.7-bin.zip

      # ⑥ ビルド実行
      - name: Build Debug APK
        run: |
          ./gradle-8.7/bin/gradle --no-daemon --stacktrace :app:assembleDebug

      # ⑦ 生成物を保存
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: |
            app/build/outputs/apk/debug/*.apk
            kt/app/build/outputs/apk/debug/*.apk
