- name: Bootstrap Gradle 8.7 (no wrapper)
  run: |
    curl -sL https://services.gradle.org/distributions/gradle-8.7-bin.zip -o g.zip
    unzip -q g.zip
    ./gradle-8.7/bin/gradle -p kt --no-daemon --no-parallel --max-workers=1 \
      --stacktrace clean :app:assembleDebug
