name: Persona Universal Build
on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: persona-${{ github.ref }}
  cancel-in-progress: true

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: 17 }
      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}
          restore-keys: gradle-${{ runner.os }}
      - name: Build Android APK
        run: ./gradlew :androidApp:assembleDebug --no-daemon --stacktrace
      - uses: actions/upload-artifact@v4
        with:
          name: Persona-Android-Debug
          path: androidApp/build/outputs/apk/debug/*.apk

  desktop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: 17 }
      - name: Build Desktop (fat jar)
        run: ./gradlew :desktopApp:build --no-daemon
      - uses: actions/upload-artifact@v4
        with:
          name: Persona-Desktop-jar
          path: desktopApp/build/libs/*.jar

  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: 17 }
      - name: Build Web (dev)
        run: ./gradlew :webApp:browserDevelopmentWebpack --no-daemon
      - uses: actions/upload-artifact@v4
        with:
          name: Persona-Web-dev
          path: webApp/build/distributions/*
