name: Persona Universal Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [android, desktop, web]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle (cache on)
        uses: gradle/actions/setup-gradle@v3

      # gradlew が無いレポでも動くように wrapper を生成
      - name: Generate Gradle wrapper if missing
        run: |
          if [ ! -f ./gradlew ]; then
            gradle wrapper --gradle-version 8.9
          fi
          chmod +x ./gradlew
          ./gradlew --version

      # --- Android -----------------------------------------------------------
      - name: Set up Android SDK
        if: matrix.target == 'android'
        uses: android-actions/setup-android@v3
      - name: Install Android packages
        if: matrix.target == 'android'
        run: |
          sdkmanager "platform-tools" \
                     "platforms;android-34" \
                     "build-tools;34.0.0"
          yes | sdkmanager --licenses

      - name: Build Android (Debug APK)
        if: matrix.target == 'android'
        run: ./gradlew :app:assembleDebug --no-daemon --stacktrace

      - name: Upload Android APK
        if: matrix.target == 'android'
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/*.apk

      # --- Desktop -----------------------------------------------------------
      - name: Build Desktop (fat jar)
        if: matrix.target == 'desktop'
        run: |
          # 好みで :desktopApp:shadowJar に置き換え可
          ./gradlew :desktopApp:build --no-daemon --stacktrace

      - name: Upload Desktop artifact
        if: matrix.target == 'desktop'
        uses: actions/upload-artifact@v4
        with:
          name: desktop-jar
          path: desktopApp/build/libs/*.jar

      # --- Web ---------------------------------------------------------------
      - name: Build Web
        if: matrix.target == 'web'
        run: |
          # プラグインによりタスク名が異なるので自動判定
          if ./gradlew -q :webApp:tasks --all | grep -q "browserDevelopmentWebpack"; then
            ./gradlew :webApp:browserDevelopmentWebpack --no-daemon --stacktrace
          elif ./gradlew -q :webApp:tasks --all | grep -q "jsBrowserDistribution"; then
            ./gradlew :webApp:jsBrowserDistribution --no-daemon --stacktrace
          else
            echo "Web build task not found. Please adjust module/task names." && exit 1
          fi

      - name: Upload Web bundle
        if: matrix.target == 'web'
        uses: actions/upload-artifact@v4
        with:
          name: web-bundle
          path: |
            webApp/build/distributions/*
            webApp/build/*/*.zip
