name: Persona Universal Build
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [ android, desktop, web ]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.9

      - name: Build (${{ matrix.target }})
        run: |
          case "${{ matrix.target }}" in
            android) gradle :app:assembleDebug --stacktrace ;;
            desktop) gradle :desktopApp:build --stacktrace ;;
            web)     gradle :webApp:browserDevelopmentWebpack --stacktrace ;;
          esac

      - name: Upload (${{ matrix.target }})
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}-artifact
          path: |
            app/build/outputs/apk/debug/*.apk
            desktopApp/build/libs/*.jar
            webApp/build/distributions/**
