name: Persona Universal Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          # ←モジュール名が違う場合は task を差し替えてね（下に代替例あり）
          - id: android
            task: ":app:assembleDebug"
            artifact: "app/build/outputs/apk/debug/*.apk"
          - id: desktop
            task: ":desktopApp:build"
            artifact: "desktopApp/build/libs/*-all.jar"
          - id: web
            task: ":webApp:browserDevelopmentWebpack"
            artifact: "webApp/build/dist/**"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # Android SDK（ライセンス自動同意込み）
      - name: Setup Android SDK
        if: matrix.id == 'android'
        uses: android-actions/setup-android@v3

      # 公式 Gradle Action（gradlew 不要・自動キャッシュ）
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: false

      - name: Show projects (debug)
        run: gradle projects

      - name: Build ${{ matrix.id }}
        run: gradle ${{ matrix.task }} --no-daemon --stacktrace

      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.id }}
          path: ${{ matrix.artifact }}
