name: Web Build
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.9
      - name: Build web
        run: |
          gradle :webApp:browserDevelopmentWebpack --stacktrace
      - name: Upload web artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: webApp/build/distributions/**
